[versions]
jooq = "3.18.25"
kotlin = "2.1.20"
kotlinxCoroutines = "1.10.1"
ktlint = "0.47.1"
misk = "2025.10.30.215657-dfc49f0"
okhttp = "5.1.0"
sqldelight = "2.1.0"
wire = "5.3.5"

[libraries]
apacheCommonsLang3 = { module = "org.apache.commons:commons-lang3", version = "3.12.0" }
assertj = { module = "org.assertj:assertj-core", version = "3.25.3" }
aws2Dynamodb = { module = "software.amazon.awssdk:dynamodb", version = "2.17.267" }
aws2DynamodbEnhanced = { module = "software.amazon.awssdk:dynamodb-enhanced", version = "2.17.267" }
awsDynamodb = { module = "com.amazonaws:aws-java-sdk-dynamodb", version = "1.11.960" }
awsS3 = { module = "com.amazonaws:aws-java-sdk-s3", version = "1.12.231" }
aws2S3 = { module = "software.amazon.awssdk:s3", version = "2.17.267" }
buildConfigPlugin = { module = "com.github.gmazzo:gradle-buildconfig-plugin", version = "3.1.0" }
dokkaGradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.9.20" }
guava = { module = "com.google.guava:guava", version = "33.4.8-jre" }
guice = { module = "com.google.inject:guice", version = "6.0.0" }
jCommander = { module = "com.beust:jcommander", version = "1.72" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.13.3" }
jacksonDataformatYaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version = "2.13.3" }
jacksonJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version = "2.13.3" }
jacksonKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version = "2.13.3" }
jettyServer = { module = "org.eclipse.jetty:jetty-server", version = "10.0.24" }
jettyServlet = { module = "org.eclipse.jetty:jetty-servlet", version = "10.0.24" }
jettyWebsocketServer = { module = "org.eclipse.jetty.websocket:websocket-jetty-server", version = "10.0.24" }
jettyWebsocketServlet = { module = "org.eclipse.jetty.websocket:websocket-servlet", version = "10.0.24" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.9.1" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.9.1" }
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.9.1" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version = "1.4.11" }
loggingApi = { module = "io.github.microutils:kotlin-logging", version = "2.1.23" }
mavenPublishGradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.31.0" }
metricsCore = { module = "io.dropwizard.metrics:metrics-core", version = "4.0.2" }
metricsParent = { module = "io.dropwizard.metrics:metrics-parent", version = "4.0.2" }
moshiCore = { module = "com.squareup.moshi:moshi", version = "1.13.0" }
moshiKotlin = { module = "com.squareup.moshi:moshi-kotlin", version = "1.13.0" }
mysql = { module = "mysql:mysql-connector-java", version = "8.0.30" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okHttpMockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version = "3.9.1" }
openTracing = { module = "io.opentracing:opentracing-api", version = "0.33.0" }
openTracingMock = { module = "io.opentracing:opentracing-mock", version = "0.33.0" }
openTracingOkHttp = { module = "io.opentracing.contrib:opentracing-okhttp3", version = "3.0.0" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version = "3.0.0" }
retrofitGuavaAdapter = { module = "com.squareup.retrofit2:adapter-guava", version = "3.0.0" }
retrofitMock = { module = "com.squareup.retrofit2:retrofit-mock", version = "3.0.0" }
retrofitMoshi = { module = "com.squareup.retrofit2:converter-moshi", version = "3.0.0" }
retrofitWire = { module = "com.squareup.retrofit2:converter-wire", version = "3.0.0" }
shadowJarPlugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version = "8.3.9" }
slf4jApi = { module = "org.slf4j:slf4j-api", version = "2.0.3" }
sqldelightGradlePlugin = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqldelightJdbcDriver = { module = "app.cash.sqldelight:jdbc-driver", version.ref = "sqldelight" }
sqldelightMysqlDialect = { module = "app.cash.sqldelight:mysql-dialect", version.ref = "sqldelight" }
spotlessPlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.12.0" }
tracingJaeger = { module = "io.jaegertracing:jaeger-core", version = "1.1.0" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
kotlinAllOpenPlugin = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.18.1" }
kotlinReflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesLogging = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinxHtml = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version = "0.12.0" }
misk = { module = "com.squareup.misk:misk", version.ref = "misk" }
miskActions = { module = "com.squareup.misk:misk-actions", version.ref = "misk" }
miskAdmin = { module = "com.squareup.misk:misk-admin", version.ref = "misk" }
miskAuditClient = { module = "com.squareup.misk:misk-audit-client", version.ref = "misk" }
miskAwsDynamodb = { module = "com.squareup.misk:misk-aws-dynamodb", version.ref = "misk" }
miskAws2Dynamodb = { module = "com.squareup.misk:misk-aws2-dynamodb", version.ref = "misk" }
miskCore = { module = "com.squareup.misk:misk-core", version.ref = "misk" }
miskHibernate = { module = "com.squareup.misk:misk-hibernate", version.ref = "misk" }
miskHibernateTesting = { module = "com.squareup.misk:misk-hibernate-testing", version.ref = "misk" }
miskHotwire = { module = "com.squareup.misk:misk-hotwire", version.ref = "misk" }
miskJdbc = { module = "com.squareup.misk:misk-jdbc", version.ref = "misk" }
miskInject = { module = "com.squareup.misk:misk-inject", version.ref = "misk" }
miskLogging = { module = "com.squareup.misk:misk-logging", version.ref = "misk" }
miskMetrics = { module = "com.squareup.misk:misk-metrics", version.ref = "misk" }
miskService = { module = "com.squareup.misk:misk-service", version.ref = "misk" }
miskSlack = { module = "com.squareup.misk:misk-slack", version.ref = "misk" }
miskTailwind = { module = "com.squareup.misk:misk-tailwind", version.ref = "misk" }
miskTesting = { module = "com.squareup.misk:misk-testing", version.ref = "misk" }
miskGrpcReflect = { module = "com.squareup.misk:misk-grpc-reflect", version.ref = "misk" }
miskVitess = { module = "com.squareup.misk:misk-vitess" }
wireCompiler = { module = "com.squareup.wire:wire-compiler", version.ref = "wire" }
wireGradlePlugin = { module = "com.squareup.wire:wire-gradle-plugin", version.ref = "wire" }
wireGrpcClient = { module = "com.squareup.wire:wire-grpc-client", version.ref = "wire" }
wireMoshiAdapter = { module = "com.squareup.wire:wire-moshi-adapter", version.ref = "wire" }
wireRuntime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wireSchema = { module = "com.squareup.wire:wire-schema", version.ref = "wire" }
wispDeployment = { module = "app.cash.wisp:wisp-deployment", version.ref = "misk" }
wispMoshi = { module = "app.cash.wisp:wisp-moshi", version.ref = "misk" }
